services:
  # synthea:
  #   image: intersystemsdc/irisdemo-base-synthea:version-1.3.4
  #   restart: "no"
  #   volumes:
  #     - ./output:/output
  #   env_file:
  #     - .env.dev
  #   command: [
  #     "-p", "100",
  #     "--exporter.csv.export=true",
  #     "--exporter.fhir.export", "false",
  #     "--exporter.baseDirectory", "/output",
  #     "--generate.demographics.socioeconomic", "true",
  #     "--generate.lookup_tables", "true",
  #     "Massachusetts"
  #   ]
  #   networks:
  #     - triage-network

  ollama:
    image: ollama/ollama:latest
    restart: "no"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      # Performance tuning (client enforces num_ctx)
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-30m}
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - triage-network

  ollama-downloader:
    image: curlimages/curl:latest
    restart: "no"
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - triage-network
    command: >
      sh -c "curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3.2:1b\"}' -H 'Content-Type: application/json'"
networks:
  triage-network:
    driver: bridge

volumes:
  ollama_data: