services:
  # synthea:
  #   image: intersystemsdc/irisdemo-base-synthea:version-1.3.4
  #   restart: "no"
  #   volumes:
  #     - ./output:/output
  #   env_file:
  #     - .env.dev
  #   command: [
  #     "-p", "100",
  #     "--exporter.csv.export=true",
  #     "--exporter.fhir.export", "false",
  #     "--exporter.baseDirectory", "/output",
  #     "--generate.demographics.socioeconomic", "true",
  #     "--generate.lookup_tables", "true",
  #     "Massachusetts"
  #   ]
  #   networks:
  #     - triage-network

  triage-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   # Python app
      - "11434:11434" # Ollama API
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ollama_data:/root/.ollama
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=0.0.0.0
    networks:
      - triage-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s  # 5 minutes to allow model download

  # Hospital simulation service - runs main.py after triage-app is ready
  hospital-simulation:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      triage-app:
        condition: service_healthy
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=triage-app
    networks:
      - triage-network
    command: python main.py
    restart: "no"

  # Test service to run LLM triage (optional)
  triage-test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      triage-app:
        condition: service_healthy
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=triage-app
    networks:
      - triage-network
    command: python src/triage/llm_triage_system/llm_triage_system.py
    profiles:
      - test

networks:
  triage-network:
    driver: bridge

volumes:
  ollama_data: