services:
  # Ollama service for LLM inference
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - triage-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s  # 5 minutes to allow model download
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull hf.co/mradermacher/docmap-uk-triage-merged-qwen2.5-7b-GGUF:Q2_K && 
             wait"

  # Hospital simulation service - runs main.py after ollama is ready
  hospital-simulation:
    image: python:3.11-slim
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - .:/app
      - ./output:/app/output
      - ./logs:/app/logs
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - OLLAMA_API_URL=http://ollama:11434/api/v1
    networks:
      - triage-network
    command: >
      sh -c "pip install -r requirements.txt && 
             python main.py"
    restart: "no"

networks:
  triage-network:
    driver: bridge

volumes:
  ollama_data: