services:
  synthea:
    image: intersystemsdc/irisdemo-base-synthea:version-1.3.4
    volumes:
      - ./output:/output
    command: [
      "-p", "100",
      "--exporter.csv.export=true",
      "--exporter.fhir.export", "false",
      "--exporter.baseDirectory", "/output",
      "--generate.demographics.socioeconomic", "true",
      "--generate.lookup_tables", "true",
      "Massachusetts"
    ]