services:
  # Hospital simulation service - runs main.py with Hugging Face API
  hospital-simulation:
    image: python:3.11-slim

    volumes:
      - .:/app  # Mount entire project directory
    working_dir: /app
    environment:
      - PYTHONPATH=/app

      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
    networks:
      - nhs-network
    command: >
      sh -c "pip install -r requirements.txt && 
             watchmedo auto-restart --directory=./src --directory=. --pattern='*.py' --recursive -- python -u main.py"
    restart: "no"
    stdin_open: true
    tty: true


networks:
  nhs-network:
    driver: bridge